# Generated by Django 3.0.5 on 2021-04-10 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_auto_20210410_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='card_number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cvc',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='exipiry_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='fullname',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='persons',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Tour'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
