# Generated by Django 3.0.5 on 2021-04-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20210410_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='card_number',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
