# Generated by Django 3.0.5 on 2021-04-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20210418_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Successful', 'Successful'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
