# Generated by Django 3.0.5 on 2021-04-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20210418_2004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itenerary',
            new_name='Itinerary',
        ),
    ]
