# Generated by Django 3.0.5 on 2021-04-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20210418_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('message', models.TextField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('waiting for payment', 'waiting for payment'), ('Successful', 'Successful'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
